# Use Golang as the builder image
FROM golang:1.24-alpine AS builder

# Install SQLite dependency
RUN apk add --no-cache gcc musl-dev postgresql-dev upx ca-certificates

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum, then download dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download
# Copy only the required files to the builder image
COPY main.go .
COPY config/ ./config/
COPY models/ ./models/
COPY routes/ ./routes/
COPY schemas/ ./schemas/
COPY services/ ./services/
COPY utils/ ./utils/
COPY pdf/ ./pdf/
COPY gdrive/ ./gdrive/
COPY gmail/ ./gmail/

# Copy templates and static files
COPY templates/ ./templates/
COPY static/ ./static/
COPY docs/ ./docs/
# Build the Go application
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /bin/main .

# Step 2: Production Stage (Minimize the final image size)
FROM scratch

# Copy CA certificates from builder image
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Copy only the compiled binary from the builder image to the production image
COPY --from=builder /bin/main /main
#Remove .env from prod version once hosted on cloud run

COPY --from=builder /app/templates /templates
COPY --from=builder /app/static /static


# Expose the application port
EXPOSE 4200

# Set the command to run the binary
CMD ["/main"]

